# netlify.toml

[build]
  command = "hugo --gc --minify -b $URL"
  publish = "site/public"

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.24"
  TZ = "UTC"  # Set to preferred timezone

[context.production.environment]
  HUGO_VERSION = "0.147.0"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.147.0"